# Generated by Django 4.2.4 on 2023-09-06 17:42

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='member_id',
            field=models.IntegerField(default=home.models.generateMemberId),
        ),
    ]
