# Generated by Django 4.2.4 on 2023-09-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guestmodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
