# Generated by Django 4.2.4 on 2023-09-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_guest_email_alter_guest_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
