# Generated by Django 4.2.4 on 2023-09-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_guest_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='password',
        ),
    ]
