# Generated by Django 4.2.4 on 2023-09-07 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_guest_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='password',
            field=models.CharField(default='', max_length=254, validators=[django.core.validators.MinLengthValidator(2, 'Password must be at least 8 characters long')]),
        ),
    ]
