# Generated by Django 4.2.4 on 2023-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_guest_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='current_session',
            field=models.CharField(default='', max_length=254),
        ),
    ]
