# Generated by Django 4.2.4 on 2023-09-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_guestmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
