# Generated by Django 4.2.4 on 2023-09-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
