# Generated by Django 4.2.4 on 2023-09-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_guestmodel_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestmodel',
            name='member_id',
        ),
    ]
