# Generated by Django 4.2.4 on 2023-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_guestmodel_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='member_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
