# Generated by Django 4.2.4 on 2023-09-10 20:56

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_guestmodel_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='member_id',
            field=models.CharField(default=home.models.generateMemberId, max_length=10),
        ),
    ]
