# Generated by Django 4.2.4 on 2023-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_guestmodel_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
