# Generated by Django 4.2.4 on 2023-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_guestmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmodel',
            name='account_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
